### PR TITLE
Add property declarations to several functions

### PR DESCRIPTION
**Pull request by pierre-rouleau**
## Summary by CodeRabbit

* **Chores**
  * Added widespread compiler purity/side-effect annotations and refreshed file headers/copyright years across the codebase.
  * Improved internal static analysis to better detect purity/side-effect/error characteristics.
  * Added a new declaration-validation linting tool and build target to surface declaration mismatches during validation.
  * No user-facing behavior or public API changes.

### CODE REVIEW

**Comment by pierre-rouleau** [comment]
@coderabbitai The command `pel-elcode-print-properties-of-sexp-at-point` finds that a function that has nothing but a call to make-has-table is side-effect-free.  This is a bug as `make-hash-table` allocates.  Please analyze the pel-elcode.el and identify what is missing in the code to identify that a function that calls `make-has-table` cannot be side-effect-free

**Comment by pierre-rouleau** [comment]
@coderabbitai The latest code fails to build on Ubuntu-latest with Emacs 27.1 and fails with the following error:

~~~
emacs -Q --batch -L . --eval '(setq byte-compile-error-on-warn t)' -f batch-byte-compile pel-elisp-eval.el

In toplevel form:
pel-elisp-eval.el:86:4:Error: Symbol’s function definition is void: pel--eval-buffer-binding-type
~~~

The build was passing before.  It passes currently on my system with Emacs 30.2.  

I suspect the change with the declaration added to `pel--eval-buffer-binding-type ` might have triggered a byte compiler problem.

Please analyze and report the reason why the code fails and if possible propose a code change to prevent the byte compilation error.

**Comment by pierre-rouleau** [comment]
@coderabbitai After the last change the following compilation error occurs on Emacs 26.1, proabably for a similar reason:

~~~
emacs -Q --batch -L . --eval '(setq byte-compile-error-on-warn t)' -f batch-byte-compile pel-completion.el

In toplevel form:
pel-completion.el:714:53:Error: Symbol’s function definition is void: pel--available-completion-mode-mask
~~~

Please analyze and identify the root cause for this error.

**Comment by pierre-rouleau** [comment]
@coderabbitai  With the proposed changes to pel-elcode.el in the analysis of functions, the following funciton is no longer found to be `(side-effect-free t)`:

~~~
(defun pel-get-list-from-hash-of-lists-for (hash-table key)                                                                                                                                   
  "Return the list of elements associated with the KEY from the HASH-TABLE.                                                                                                                   
                                                                                                                                                                                              
The returned list holds elements in the same order as they were                                                                                                                               
entered: the first element entered in the list is the first                                                                                                                                   
element in the returned list."
  (reverse (gethash key hash-table ())))
~~~

Why is that?

**Comment by pierre-rouleau** [comment]
@coderabbitai The `pel-elcode-properties-of-sexp` has another weakness from what I can tell: when the sexp being analyzed reads the value of a user-option variable that is not taken into account and if nothing else prevents it the sexp might be identified as being `(pure t)` when it really is not since it depends on the value of the variable.

Please propose code modification to handle this.

**Comment by pierre-rouleau** [comment]
@coderabbitai Please propose the code for a new PEL linter application that can be called from the command line.  That application would process all Emacs Lisp files in the current directory and would identify any defun sexp that could have a `(declare)`  form to specify that it is pure, side-effect-free or error-free but does not have that declaration.  The application would return an exit code of 1 if it finds one function like that, and stop on the first diagnostic found.  It would exit with 0 if it finds no diagnostics.

**Comment by pierre-rouleau** [comment]
@coderabbitai  I would liek the new pel-lint-declarations.el program to be able to detect invalid declarations too.  If a defun has a declare form and that form is not appropriate, I would like the program to flag this as an error and stop.  IS this the case in your proposed code?  If not please propose modifications to its code.

**Comment by pierre-rouleau** [comment]
@coderabbitai I have changed my mind about stopping on the first error.  Please modify the code to list all detected errors.

**Comment by pierre-rouleau** [comment]
@coderabbitai I added a make support for the new `bin/pel-lint-declarations.el`.  Unfortunately the current implementation has several flaws:
- It only detects one error and it stops.  I would like it to report all errors.
- When it reports an error the line number is off (see below)
- The reports are not aways valid.  It has false positive as shown in the output below.

I ran the command by issuing the make command in a shell and I got the following:
~~~
zsh% make validate-declarations                                                                                                                                                              2 ⨯ 704ms 
emacs -Q --batch -L . -l bin/pel-lint-declarations.el --eval "(pel-lint-declarations-main)"
/Users/roup/my/dvp/elisp/pel/pel--base.el:508: function `pel-expression-p' has invalid declaration properties: pure, side-effect-free, error-free; inferred declaration is nil
make: *** [Makefile:1272: validate-declarations] Error 1
>2
~~~

- Problem 1: `pel-expression-p` is on line 515 in pel--base.el, not line 508.
- Problem 2: `pel-expression-p' should be declared as `(declare (pure t) (side-effect-free error-free))` unlike what the linter says.  The `(pel-elcode-print-properties-of-sexp-at-point)` evaluates it as `(declare (pure t) (side-effect-free error-free))`.

The code is:
~~~
 515 (defun pel-expression-p (val)
 516   "Return non-nil if VAL is an expression, nil if it is a value.                                                                                                                                   
 517 Return nil for t and nil.                                                                                                                                                                          
 518 Return t for \\='some-symbols or \\='(some expressions), nothing else.                                                                                                                             
 519 Meant to be used to identify code that is quoted (for delayed                                                                                                                                      
 520 code execution)."
 521   (declare (pure t) (side-effect-free error-free))
 522   (and (not (eq val t))
 523        (not (eq val nil))
 524        (or (symbolp val)
 525            (consp val))))
 526 
 527 (defun pel-user-option-p (symbol)
 528   "Return t when SYMBOL is a valid PEL user-option, nil otherwise."
 529   (declare (side-effect-free t))
 530   (and (custom-variable-p symbol)
 531        (eq t (compare-strings "pel-use-" nil nil
 532                               (symbol-name symbol) 0 8))))
~~~

Please analyze and report why the linter results are invalid.  Please propose code modifications to the linter code.

**Comment by pierre-rouleau** [comment]
@coderabbitai As for "The false positive is most likely caused by loading stale pel-elcode.elc"  please note that the make file has the following dependency rule on line 894:

~~~
bin/pel-lint-delclarations.elc:  pel-elcode.elc
~~~

So the the linter depending on old/stale pel-elcode.elc is not the problem.

**Comment by pierre-rouleau** [comment]
@coderabbitai. There is a problem with the Makefile.  A dependency is missing to build the elc file of the pel-int-declaration.el file.  See my attempt from a shell when the current directory is the root of the repo:

~~~
zsh% rm pel-elcode.elc bin/pel-lint-declarations.elc                                                                                                                                                                                                                                                                                                                       
rm: bin/pel-lint-declarations.elc: No such file or directory
>1
zsh% make validate-declarations                                                                                                                                                                                                                                                                                                                                               1 ⨯ 9ms 
emacs -Q --batch -L . --eval '(setq byte-compile-error-on-warn t)' -f batch-byte-compile pel-elcode.el
emacs -Q --batch -L . --eval '(setq byte-compile-error-on-warn t)' -f batch-native-compile pel-elcode.el
emacs -Q --batch -L . -L bin \
         --eval '(setq byte-compile-error-on-warn t)' \
         -f batch-byte-compile bin/pel-lint-declarations.el

In toplevel form:
bin/pel-lint-declarations.el:203:12: Error: the function ‘pel-elcode-properties-of-sexp’ is not known to be defined.
make: *** [Makefile:1167: bin/pel-lint-declarations.elc] Error 1
>2
~~~

Please analyze and propose a change to the Makefile to ensure that the bin/pel-linter-declaration.el is compiled.

**Comment by pierre-rouleau** [comment]
@coderabbitai With the changes to the Makefile:

- The linter now builds.
-  It reports all errors.
- It reports the correct line number.
- However it still has false positives.  It reports that `pel-expression-p` should not have a declaration, while executing `pel-elcode-print-properties-of-sexp-at-point` from within Emacs in pel--base.el reports that `pel-expression-p`  should have `(declare (pure t) (side-effect-free error-free))`.

Here is the complete log:
~~~
rm pel-elcode.elc bin/pel-lint-declarations.elc && make validate-declarations                                                                                                                                                    2 ⨯ 2.362s 
emacs -Q --batch -L . --eval '(setq byte-compile-error-on-warn t)' -f batch-byte-compile pel-elcode.el
emacs -Q --batch -L . --eval '(setq byte-compile-error-on-warn t)' -f batch-native-compile pel-elcode.el
emacs -Q --batch -L . -L bin \
         --eval '(setq byte-compile-error-on-warn t)' \
         -l pel-elcode \
         -f batch-byte-compile bin/pel-lint-declarations.el
emacs -Q --batch -L . -L bin \
         --eval '(setq byte-compile-error-on-warn t)' \
         -l pel-elcode \
         -f batch-native-compile bin/pel-lint-declarations.el
emacs -Q --batch -L . -l bin/pel-lint-declarations.el --eval "(pel-lint-declarations-main)"
/Users/roup/my/dvp/elisp/pel/pel--base.el:515: function `pel-expression-p' has invalid declaration properties: pure, side-effect-free, error-free; inferred declaration is nil

make: *** [Makefile:1290: validate-declarations] Error 1
>2
~~~

Please analyze and identify why the linter running from the command line gives different results from what I get from within Emacs.  Is it possible the issue has to do with the major mode?  Inside emacs the major more is `emacs-lisp-mode` not `lisp-mode`.

**Comment by pierre-rouleau** [comment]
@coderabbitai With the changes to the Makefile:

- The linter now builds.
-  It reports all errors.
- It reports the correct line number.
- However it still has false positives.  It reports that `pel-expression-p` should not have a declaration, while executing `pel-elcode-print-properties-of-sexp-at-point` from within Emacs in pel--base.el reports that `pel-expression-p`  should have `(declare (pure t) (side-effect-free error-free))`.

Here is the complete log:
~~~
rm pel-elcode.elc bin/pel-lint-declarations.elc && make validate-declarations                                                                                                                                                    2 ⨯ 2.362s 
emacs -Q --batch -L . --eval '(setq byte-compile-error-on-warn t)' -f batch-byte-compile pel-elcode.el
emacs -Q --batch -L . --eval '(setq byte-compile-error-on-warn t)' -f batch-native-compile pel-elcode.el
emacs -Q --batch -L . -L bin \
         --eval '(setq byte-compile-error-on-warn t)' \
         -l pel-elcode \
         -f batch-byte-compile bin/pel-lint-declarations.el
emacs -Q --batch -L . -L bin \
         --eval '(setq byte-compile-error-on-warn t)' \
         -l pel-elcode \
         -f batch-native-compile bin/pel-lint-declarations.el
emacs -Q --batch -L . -l bin/pel-lint-declarations.el --eval "(pel-lint-declarations-main)"
/Users/roup/my/dvp/elisp/pel/pel--base.el:515: function `pel-expression-p' has invalid declaration properties: pure, side-effect-free, error-free; inferred declaration is nil

make: *** [Makefile:1290: validate-declarations] Error 1
>2
~~~

Please analyze and identify why the linter running from the command line gives different results from what I get from within Emacs.  Is it possible the issue has to do with the major mode?  Inside emacs the major more is `emacs-lisp-mode` not `lisp-mode`.

**Comment by pierre-rouleau** [comment]
@coderabbitai With the changes to the Makefile:

- The linter now builds.
-  It reports all errors.
- It reports the correct line number.
- However it still has false positives.  It reports that `pel-expression-p` should not have a declaration, while executing `pel-elcode-print-properties-of-sexp-at-point` from within Emacs in pel--base.el reports that `pel-expression-p`  should have `(declare (pure t) (side-effect-free error-free))`.

Here is a partial log:
~~~
rm pel-elcode.elc bin/pel-lint-declarations.elc && make validate-declarations                                                                                                                                                    2 ⨯ 2.362s 
emacs -Q --batch -L . --eval '(setq byte-compile-error-on-warn t)' -f batch-byte-compile pel-elcode.el
emacs -Q --batch -L . --eval '(setq byte-compile-error-on-warn t)' -f batch-native-compile pel-elcode.el
emacs -Q --batch -L . -L bin \
         --eval '(setq byte-compile-error-on-warn t)' \
         -l pel-elcode \
         -f batch-byte-compile bin/pel-lint-declarations.el
emacs -Q --batch -L . -L bin \
         --eval '(setq byte-compile-error-on-warn t)' \
         -l pel-elcode \
         -f batch-native-compile bin/pel-lint-declarations.el
emacs -Q --batch -L . -l bin/pel-lint-declarations.el --eval "(pel-lint-declarations-main)"
/Users/roup/my/dvp/elisp/pel/pel--base.el:515: function `pel-expression-p' has invalid declaration properties: pure, side-effect-free, error-free; inferred declaration is nil

make: *** [Makefile:1290: validate-declarations] Error 1
>2
~~~

Please analyze and identify why the linter running from the command line gives different results from what I get from within Emacs.  Is it possible the issue has to do with the major mode?  Inside emacs the major more is `emacs-lisp-mode` not `lisp-mode`.
